---
title: "Final report tables"
author: "Claire Powers"
date: "2024-02-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
rm(list=ls())

### Packages
library(tidyverse)
library(lme4)
library(gt)
library(kableExtra)
library(sjPlot)

## Data ##
park.order = c("GNP","YNP","RMN","GSD","PEC")

### Read in and clean data
plantcover.us =read_csv('./AnalysisData/vascplantcover_final.csv') %>%
  filter(!is.na(start.plantCover)) %>%
  mutate(PSaspect=paste(park,summit,aspect,sep="."),
         pchangecover = (change.cover/start.plantCover)*100) %>%
  relocate(c(change.cover,pchangecover),.after = end.plantCover) %>%
    arrange(-pchangecover) %>%
  filter(pchangecover<100) %>%
  mutate(park = factor(park,levels=c("GNP","YNP","RMN","GSD","PEC")),
         tr.num = str_sub(transition,4,4))
### Create another dataframe where numeric predictor variables are scaled ###
plantcover.s = plantcover.us # Get names columns to standardize
scale_cols = plantcover.us %>% select(start.plantCover,climPC1,climPC2,sitelat,contains(c(".tmean",".aet",".pet",".ppt",".snowdays",".gdd"))) %>% names()
plantcover.s[scale_cols]=lapply(plantcover.s[scale_cols], function(x) scale(x))

sppmodelvars = c("sciname","endcover","startcover","latmean1090","sitelat","climPC1","climPC2","habit","perenneating","transition","sciname","min.gdd","min.gs.ppt","min.wy.ppt","max.tmean","park")
sppcover.orig = read_csv('./AnalysisData/analysisdata_final.csv')
sppcover.unscaled=sppcover.orig %>% 
  drop_na(startcover,climPC1,climPC2,latmax1090,latmin1090,latmean1090,latmedian1090) %>% 
  filter(abs(changecover)<=10) %>% # remove suspiciously large changes as these are likely associated with misIDed spp
  filter(startcover+endcover!=0) %>%  # remove cases where a species did not have start and end cover
  mutate(parksummit = paste(park,summit,sep="."),
         PSaspect = paste(park,summit,aspect,sep="."),
         startcovcats = cut(startcover,breaks=c(-0.1,seq(0.1,40,5)))) #%>% 
  # select(all_of(sppmodelvars),genus,changecover,aspect,summit,startyear) %>% 


# Create another dataframe where numeric predictor variables are scaled
sppcover.scaled = sppcover.unscaled# Get names columns to standardize
scale_cols = sppcover.unscaled %>% select(startcover,climPC1,climPC2,sitelat,contains(c("1090",".tmean",".aet",".pet",".ppt",".snowdays",".gdd"))) %>% names()
sppcover.scaled[scale_cols]=lapply(sppcover.scaled[scale_cols], function(x) scale(x))
sppcover.scaled = sppcover.scaled %>% 
  mutate(startcover.unscaled=sppcover.unscaled$startcover,
         latmean1090.unscaled = sppcover.unscaled$latmean1090,
         sitelat.unscaled=sppcover.unscaled$sitelat)

sppcover.unscaled$changecover = sppcover.unscaled$endcover-sppcover.unscaled$startcover
rm(scale_cols)

## Models ##
climPC.mod.str = "endcover ~ startcover*(climPC1 + latmean1090 + I(latmean1090^2) + sitelat) + climPC2*perenneating + habit*climPC1 + habit*sitelat + (1 | transition) + (climPC1 + climPC2 | sciname)"
climPC.mod.s = lmer(formula = climPC.mod.str, na.action = "na.fail", data = sppcover.scaled, REML = T)
climPC.mod.us = lmer(formula = climPC.mod.str, na.action = "na.fail", data = sppcover.unscaled, REML = T)

# Best explicit climate variable model
# model string
climVar.mod.str = "endcover ~ startcover*(latmean1090 + I(latmean1090^2) + min.gdd + min.gs.ppt + min.wy.ppt + sitelat) + habit*(min.gdd + sitelat) + perenneating*max.tmean + (1 | transition) + (max.tmean + min.wy.ppt + min.gs.ppt + min.gdd | sciname)"

# Refit with REML
climVar.mod.s = lmer(formula = climVar.mod.str, na.action = "na.fail", data = sppcover.scaled, REML = T)
climVar.mod.us = lmer(formula = climVar.mod.str, na.action = "na.fail", data = sppcover.unscaled, REML = T)
rm(climPC.mod.str,climVar.mod.str)


climPC.plantCover.mod.us = lmer(end.plantCover~start.plantCover*(climPC1+climPC2+sitelat) + park + (1|transition), na.action = "na.fail",data = na.omit(plantcover.us),REML = TRUE)

climVar.plantCover.mod.us = lmer(formula = end.plantCover ~ max.snowdays + mean.gs.ppt + min.wy.ppt + park + start.plantCover + max.snowdays:start.plantCover + mean.gs.ppt:start.plantCover + min.wy.ppt:start.plantCover + (1 | transition), data = plantcover.us, REML = FALSE, na.action = "na.fail")
```


##  Species info table
```{r sppInfo}

df = sppcover.unscaled %>% 
  dplyr::select("Species"=sciname,sciname,Park = park,taxunit,habit,"perennating"=perenneating,leaves) %>% 
  mutate(Park = case_when(Park=="GNP"~"GLAC",
                          Park=="YNP"~"YELL",
                          Park=="RMN"~"ROMO",
                          Park=="GSD"~"GRSD",
                          Park=="PEC"~"PECO"))

parks = aggregate(Park ~ Species,unique(df),paste,collapse=", ")

df2 = df %>% 
  group_by(Species) %>% 
  reframe(N = n(),
          `Taxonomic unit` = unique(taxunit),
          Habit=unique(habit),
          Perennating = unique(perennating),
          Leaves = unique(leaves)) %>% 
  merge(parks,.,by="Species")
write_csv(df2,"Results/FinalTables/speciesInfo.csv")
```

