---
title: "May 2023 Best Models"
author: "Claire Powers"
date: '2023-05-07'
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages and data
```{r start}
rm(list=ls())

### Packages
library(tidyverse)
library(lme4)
library(MuMIn)
library(rje)
library(parallel)
library(forcats)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(performance)
library(ggfortify)
library(modelsummary)

### Read in and clean data
dats.orig = read_csv('Data/AnalysisData/specieslevel_analysisdata_final.csv')
dats=dats.orig %>% 
  drop_na(startcover,climPC1,climPC2,latmax1090,latmin1090,latmean1090,latmedian1090) %>% 
  filter(abs(changecover)<=10) %>% # remove suspiciously large changes as these are likely associated with misIDed spp
  filter(startcover+endcover!=0) %>%  # remove cases where a species did not have start or end cover
  mutate(parksummit = paste(park,summit,sep="."),
         PSaspect = paste(park,summit,aspect,sep="."),
         startcovcats = cut(startcover,breaks=c(-0.1,seq(0.1,40,5))))

dats$park = factor(dats$park,levels=c("GNP","YNP","RMN","GSD","PEC"))

# Create another dataframe where numeric predictor variables are scaled
dats.scaled = dats# Get names columns to standardize
scale_cols = dats %>% select(startcover,climPC1,climPC2,sitelat,contains(c("1090",".tmean",".aet",".pet",".ppt",".snowdays",".gdd"))) %>% names()
dats.scaled[scale_cols]=lapply(dats.scaled[scale_cols], function(x) scale(x))

traits = read_csv("./Data/speciesTraits/allparks_speclist_20220124 traits.csv")
siteinfo=read_csv("./Data/siteInfo/summitcoordinates.csv")
siteinfo$park = factor(x = siteinfo$park,levels=c("GNP","YNP","RMN","GSD","PEC"))

rm(scale_cols)
```

###### Best models ######

Climate PC model
## Best model with climate PC axes
$$endcover \sim startcover*(climPC1 + latmean1090 + latmean1090^2 + sitelat) + climPC2*perenneating + habit*climPC1 + habit*sitelat +\\(1 | transition) + (climPC1 + climPC2 | sciname)$$

```{r best.climPC.mod.scaled}

# Simplified model call from dredge output
climPC.mod.str = "endcover ~ startcover*(climPC1 + latmean1090 + I(latmean1090^2) + sitelat) + climPC2*perenneating + habit*climPC1 + habit*sitelat + (1 | transition) + (climPC1 + climPC2 | sciname)"

# Scaled data
climPC.mod.s = lmer(formula = climPC.mod.str, na.action =  "na.fail", data = dats.scaled, REML = T)
summary(climPC.mod.s)

# Refit with REML 
climPC.mod.us = lmer(formula = climPC.mod.str, na.action =  "na.fail", data = dats, REML = T)
summary(climPC.mod.us)

plot_model(climPC.mod.us,show.p = T,show.legend = T,show.values = T,value.offset = c(0.35),title="Unscaled data")+theme_bw(base_size = 14)
tab_model(climPC.mod.us,digits = 4)
```

--- Climate variable model ---
$$endcover \sim startcover*(latmean1090 + latmean1090^2 + min.gdd + min.gs.ppt + min.wy.ppt + sitelat) + habit*(min.gdd + sitelat) + perenneating*max.tmean +\\ (1 | transition) + (max.tmean + min.wy.ppt + min.gs.ppt + min.gdd | sciname)$$
# Climate variable model fit with scaled data

```{r best.ClimVar.mod.scaled}

# Simplified model call from dredge output
climVar.mod.str = "endcover ~ startcover*(latmean1090 + I(latmean1090^2) + min.gdd + min.gs.ppt + min.wy.ppt + sitelat) + habit*(min.gdd + sitelat) + perenneating*max.tmean + (1 | transition) + (max.tmean + min.wy.ppt + min.gs.ppt + min.gdd | sciname)"

# Scaled data
climVar.mod.s = lmer(formula = climVar.mod.str, na.action =  "na.fail", data = dats.scaled, REML = T)

# unscaled
climVar.mod.us = lmer(formula = climVar.mod.str, na.action =  "na.fail", data = dats, REML = T)

plot_model(climVar.mod.s,show.p = T,show.legend = T,show.values = T,value.offset = c(0.35),title="Scaled data")+theme_bw(base_size = 14)
plot_model(climVar.mod.s,show.p = T,show.legend = T,show.values = T,value.offset = c(0.35),axis.lim = c(-2,2))+theme_bw(base_size = 14)

tab_model(climVar.mod.s)


# Climate variable model output with unscaled data
plot_model(climVar.mod.us,show.p = T,show.legend = T,show.values = T,value.offset = c(0.35),title = "Unscaled data")+theme_bw(base_size = 14)
plot_model(climVar.mod.us,show.p = T,show.legend = T,show.values = T,value.offset = c(0.35),axis.lim = c(-2,2))+theme_bw(base_size = 14)

tab_model(climVar.mod.us,digits=4)

```
