---
title: "May 2023 Best Models"
author: "Claire Powers"
date: '2023-05-07'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages and data
```{r start}
rm(list=ls())

### Packages
library(tidyverse)
library(lme4)
library(MuMIn)
library(rje)
library(parallel)
library(forcats)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(performance)
library(ggfortify)
library(modelsummary)

### Read in and clean data
dats.orig = read_csv('./AnalysisData/analysisdata_final.csv')
dats=dats.orig %>% 
  drop_na(startcover,climPC1,climPC2,latmax1090,latmin1090,latmean1090,latmedian1090) %>% 
  filter(abs(changecover)<=10) %>% # remove suspiciously large changes as these are likely associated with misIDed spp
  filter(startcover+endcover!=0) %>%  # remove cases where a species did not have start or end cover
  mutate(parksummit = paste(park,summit,sep="."),
         PSaspect = paste(park,summit,aspect,sep="."),
         startcovcats = cut(startcover,breaks=c(-0.1,seq(0.1,40,5))))

dats$park = factor(dats$park,levels=c("GNP","YNP","RMN","GSD","PEC"))

# Create another dataframe where numeric predictor variables are scaled
dats.scaled = dats# Get names columns to standardize
scale_cols = dats %>% select(startcover,climPC1,climPC2,sitelat,contains(c("1090",".tmean",".aet",".pet",".ppt",".snowdays",".gdd"))) %>% names()
dats.scaled[scale_cols]=lapply(dats.scaled[scale_cols], function(x) scale(x))
# not_all_na <- function(x) any(!is.na(x))

traits = read_csv("./InputData/speciesTraits/allparks_speclist_20220124 traits.csv")
siteinfo=read_csv("./InputData/siteInfo/summitcoordinates.csv")
siteinfo$park = factor(x = siteinfo$park,levels=c("GNP","YNP","RMN","GSD","PEC"))

rm(scale_cols)
```

###### Best models ######

Climate PC model
## Best model with climate PC axes
$$endcover \sim startcover*(climPC1 + latmean1090 + latmean1090^2 + sitelat) + climPC2*perenneating + habit*climPC1 + habit*sitelat +\\(1 | transition) + (climPC1 + climPC2 | sciname)$$

```{r best.climPC.mod.scaled}

# Simplified model call from dredge output
climPC.mod.str = "endcover ~ startcover*(climPC1 + latmean1090 + I(latmean1090^2) + sitelat) + climPC2*perenneating + habit*climPC1 + habit*sitelat + (1 | transition) + (climPC1 + climPC2 | sciname)"

climPC.mod.str2 = "endcover ~ startcover*(climPC1 + latmean1090 + I(latmean1090^2) + sitelat) + climPC2*perenneating + habit*climPC1 + habit*sitelat + (1 | transition) + (climPC1 + climPC2 | sciname)"

# Scaled data
climPC.mod.s = lmer(formula = climPC.mod.str, na.action =  "na.fail", data = dats.scaled, REML = T)
summary(climPC.mod.s)

# Refit with REML 
climPC.mod.us2 = lmer(formula = climPC.mod.str, na.action =  "na.fail", data = dats, REML = T)
summary(climPC.mod.us)
```

```{r plot.climPC.mod.scaled}

plot_model(climPC.mod.us,show.p = T,show.legend = T,show.values = T,value.offset = c(0.35),title="Unscaled data")+theme_bw(base_size = 14)
plot_model(climPC.mod.us,show.p = T,show.legend = T,show.values = T,value.offset = c(0.35),title="Unscaled data")+theme_bw(base_size = 14)
tab_model(climPC.mod.s,digits = 4)

```


## GGplot version of forest plot
```{r ggForest.climPCA}

# plot_model(climPC.mod.s,show.p = T,show.values = T)+
#   theme_bw()
# 
# climPC.df = broom.mixed::tidy(x = climPC.mod.us) %>%
#   filter(effect=="fixed") %>%
#   select(-c(effect,group)) %>%
#   filter(term!="(Intercept)")
# write_csv(climPC.df,"Results/FixedEffects/climPCfixedeffects_unscaled.csv")
climPC.plotdf = read_csv("./Results/FixedEffects/climPCfixedeffects_unscaled_formatted.csv")
summary(climPC.plotdf)

climPC.plotdf$full.name = factor(climPC.plotdf$full.name,levels=climPC.plotdf$full.name)
climPC.plotdf$full.name

summary(climPC.plotdf)

ggplot(climPC.plotdf,aes(x=estimate,y=full.name,color=estimate>0))+
  geom_vline(xintercept = 0,color="grey70",linetype="dashed")+
  geom_point(size=2)+
  geom_errorbar(aes(xmin=estimate-std.error*1.96,xmax=estimate+std.error*1.96),width=0.25)+
  theme_classic(base_size = 12)+
  labs(x = "Estimate", y = "")+
  theme(legend.position = "none")+
  coord_cartesian(xlim=c(-4.3,4.3))+
  scale_x_continuous(breaks=seq(-4,4,2))+
  scale_color_manual(values=c("red3","dodgerblue3"))+
  scale_y_discrete(limits=rev(levels(climPC.plotdf$full.name)),expand=c(0,1))# +
  # geom_text(aes(label=label),vjust=-0.5)
ggsave("Results/FixedEffects/climPC_FEforestplots_unscaled.png",dpi=300,h=5,w=8)
# 
# r.plot = ggplot(climPC.plotdf,aes(color=estimate>0))+
#   scale_color_manual(values=c("red3","dodgerblue3"))+
#   scale_y_discrete(limits=rev(levels(climPC.plotdf$full.name)))+
#   theme_void()+
#   geom_text(aes(x=0,y=full.name,label=label),hjust=0,size=3)+
#   theme(legend.position = "none")
# 
# layout = c(
#   area(t = 1, l = 0, b = 30, r = 9), # middle plot starts a little lower (t=1) because there's no title. starts 1 unit right of the left plot (l=4, whereas left plot is r=3), goes to the bottom of the page (30 units), and 6 units further over from the left plot (r=9 whereas left plot is r=3)
#   area(t = 0, l = 8, b = 30, r = 11) # right most plot starts at top of page, begins where middle plot ends (l=9, and middle plot is r=9), goes to bottom of page (b=30), and extends two units wide (r=11)
# )
# 
# l.plot + r.plot + plot_layout(design = layout)
```


--------------
---Climate variable model---
$$endcover \sim startcover*(latmean1090 + latmean1090^2 + min.gdd + min.gs.ppt + min.wy.ppt + sitelat) + habit*(min.gdd + sitelat) + perenneating*max.tmean +\\ (1 | transition) + (max.tmean + min.wy.ppt + min.gs.ppt + min.gdd | sciname)$$
# Climate variable model fit with scaled data

```{r best.ClimVar.mod.scaled}

# Simplified model call from dredge output
climVar.mod.str = "endcover ~ startcover*(latmean1090 + I(latmean1090^2) + min.gdd + min.gs.ppt + min.wy.ppt + sitelat) + habit*(min.gdd + sitelat) + perenneating*max.tmean + (1 | transition) + (max.tmean + min.wy.ppt + min.gs.ppt + min.gdd | sciname)"

# Scaled data
climVar.mod.s = lmer(formula = climVar.mod.str, na.action =  "na.fail", data = dats.scaled, REML = T)

# unscaled
climVar.mod.us = lmer(formula = climVar.mod.str, na.action =  "na.fail", data = dats, REML = T)

# summary(best.climVar.mod)
# as.data.frame(VarCorr(best.climVar.mod))
# r2(climVar.mod)
# check_singularity(climVar.mod)
# tab_model(climVar.mod)
```


## GGplot version of forest plot
```{r ggForest.climVar}
# climVar.df = broom.mixed::tidy(x = climVar.mod.us) %>% 
#   filter(effect=="fixed") %>% 
#   select(-c(effect,group)) %>% 
#   filter(term!="(Intercept)")
# write_csv(climVar.df,"Results/FixedEffects/climVarfixedeffects_unscaled.csv")

climVar.plotdf = read_csv("Results/FixedEffects/climVarfixedeffects_unscaled_formatted.csv")
summary(climVar.plotdf$estimate)

climVar.plotdf$full.name = factor(climVar.plotdf$full.name,levels=climVar.plotdf$full.name)
climVar.plotdf$full.name

summary(climVar.plotdf)

ggplot(climVar.plotdf,aes(x=estimate,y=full.name,color=estimate>0))+
  geom_vline(xintercept = 0,color="grey70",linetype="dashed")+
  geom_point(size=2)+
  geom_errorbar(aes(xmin=estimate-std.error*1.96,xmax=estimate+std.error*1.96),width=0.25)+
  theme_classic(base_size = 12)+
  labs(x = "Estimate", y = "")+
  theme(legend.position = "none")+
  coord_cartesian(xlim=c(-2.25,2.25))+
  scale_color_manual(values=c("red3","dodgerblue3"))+
  scale_y_discrete(limits=rev(levels(climVar.plotdf$full.name)),expand=c(0,1))# +
  # geom_text(aes(label=label),vjust=-0.5)
ggsave("Results/FixedEffects/climVar_FEforestplots_unscaled.png",dpi=300,h=5,w=8)

# 
# r.plot = ggplot(climVar.plotdf,aes(color=estimate>0))+
#   scale_color_manual(values=c("red3","dodgerblue3"))+
#   scale_y_discrete(limits=rev(levels(climVar.plotdf$full.name)))+
#   theme_void()+
#   geom_text(aes(x=0,y=full.name,label=label),hjust=0,size=3)+
#   theme(legend.position = "none")
# 
# layout = c(
#   area(t = 1, l = 0, b = 30, r = 9), # middle plot starts a little lower (t=1) because there's no title. starts 1 unit right of the left plot (l=4, whereas left plot is r=3), goes to the bottom of the page (30 units), and 6 units further over from the left plot (r=9 whereas left plot is r=3)
#   area(t = 0, l = 8, b = 30, r = 11) # right most plot starts at top of page, begins where middle plot ends (l=9, and middle plot is r=9), goes to bottom of page (b=30), and extends two units wide (r=11)
# )
# 
# l.plot + r.plot + plot_layout(design = layout)
```



# Climate variable model output with scaled data
```{r plot.climvar.FEs.scaled}
plot_model(climVar.mod.s,show.p = T,show.legend = T,show.values = T,value.offset = c(0.35),title="Scaled data")+theme_bw(base_size = 14)
plot_model(climVar.mod.s,show.p = T,show.legend = T,show.values = T,value.offset = c(0.35),axis.lim = c(-2,2))+theme_bw(base_size = 14)

tab_model(climVar.mod.s)

plot_model(climVar.mod.s,type="re",group.terms = )
```

# Climate variable model output with unscaled data
```{r plot.climvar.FEs.scaled}
plot_model(climVar.mod.us,show.p = T,show.legend = T,show.values = T,value.offset = c(0.35),title = "Unscaled data")+theme_bw(base_size = 14)
plot_model(climVar.mod.us,show.p = T,show.legend = T,show.values = T,value.offset = c(0.35),axis.lim = c(-2,2))+theme_bw(base_size = 14)

tab_model(climVar.mod.us,digits=4)

plot_model(climVar.mod.us,type="re")
```

-----

##  Random effects ##

```{r climPCREs}
climPC.REs = ranef(climPC.mod.us,condVar=T) %>% as.data.frame()
```

```{r climPCREs.transition}
pc.transitions = filter(climPC.REs,grpvar=="transition") %>% 
  select(transition=grp,condval,condsd) %>% 
  mutate(summit=str_sub(transition,1,3),
         tr.num = str_sub(transition,4,4)) %>% 
  merge(siteinfo,by="summit")

ggplot(pc.transitions,aes(x=reorder(summit,elev),y=condval))+
  geom_hline(yintercept = 0,color="red")+
  geom_point()+
  facet_grid(tr.num~park,scales ="free_x")+
  theme_bw()

ggplot(pc.transitions,aes(x=elev,y=lat,color=condval))+
  geom_point(size=3) + 
  scale_color_distiller(type="div")+
  theme_bw()

```


```{r climPCREs.species}
sciname.ints.pc = filter(climPC.REs,grpvar=="sciname",term=="(Intercept)") %>% 
  select(-grpvar) %>% dplyr::rename(sciname=grp) %>% 
  mutate(lower.95ci = condval-condsd*1.96,
         upper.95ci = condval+condsd*1.96,
         nonzero.95ci = ifelse(lower.95ci<0&upper.95ci>0,0,1),
         lower.80ci = condval-condsd*1.23,
         upper.80ci = condval+condsd*1.23,
         nonzero.80ci = ifelse(lower.80ci<0&upper.80ci>0,0,1)) %>% filter(nonzero.80ci==1)

sciname.climPC1 = filter(climPC.REs,grpvar=="sciname",term=="climPC1") %>% 
  select(-grpvar) %>% dplyr::rename("sciname"=grp) %>% 
  mutate(lower.95ci = condval-condsd*1.96,
         upper.95ci = condval+condsd*1.96,
         nonzero.95ci = ifelse(lower.95ci<0&upper.95ci>0,0,1),
         lower.80ci = condval-condsd*1.23,
         upper.80ci = condval+condsd*1.23,
         nonzero.80ci = ifelse(lower.80ci<0&upper.80ci>0,0,1)) %>% filter(nonzero.80ci==1)

sciname.climPC2 = filter(climPC.REs,grpvar=="sciname",term=="climPC2") %>% 
  select(-grpvar) %>% dplyr::rename("sciname"=grp) %>% 
  mutate(lower.95ci = condval-condsd*1.96,
         upper.95ci = condval+condsd*1.96,
         nonzero.95ci = ifelse(lower.95ci<0&upper.95ci>0,0,1),
         lower.80ci = condval-condsd*1.23,
         upper.80ci = condval+condsd*1.23,
         nonzero.80ci = ifelse(lower.80ci<0&upper.80ci>0,0,1)) %>% filter(nonzero.80ci==1)

climPC.nonZeros = filter(select(sciname.ints.pc,-term),nonzero.80ci==1) %>% 
  merge(., filter(select(sciname.climPC1,-term),nonzero.80ci==1),by="sciname",suffixes=c(".int",".pc1"),all=T) %>% 
  merge(., filter(select(sciname.climPC2,-term),nonzero.80ci==1),by="sciname",suffixes=c("",".pc2"),all=T) 

```


```{r climVarREs}

climvarREs = ranef(climVar.mod.us,condVar=T) %>% as.data.frame()
climvarRE.ssp = filter(climvarREs,grpvar=="sciname") %>% 
  rename(sciname=grp) %>% 
  merge(.,traits,by="sciname")
climvarRE.tr = filter(climvarREs,grpvar=="transition")

sciname.intercepts = filter(climvarREs,grpvar=="sciname",term=="(Intercept)") %>% 
  select(-grpvar) %>% dplyr::rename("sciname"=grp) %>% 
  mutate(lower.95ci = condval-condsd*1.96,
         upper.95ci = condval+condsd*1.96,
         nonzero.95ci = ifelse(lower.95ci<0&upper.95ci>0,0,1),
         lower.80ci = condval-condsd*1.23,
         upper.80ci = condval+condsd*1.23,
         nonzero.80ci = ifelse(lower.80ci<0&upper.80ci>0,0,1)) %>% filter(nonzero.80ci==1)

sciname.maxTmean = filter(climvarREs,grpvar=="sciname",term=="max.tmean") %>% 
  select(-grpvar) %>% dplyr::rename("sciname"=grp) %>% 
  mutate(lower.95ci = condval-condsd*1.96,
         upper.95ci = condval+condsd*1.96,
         nonzero.95ci = ifelse(lower.95ci<0&upper.95ci>0,0,1),
         lower.80ci = condval-condsd*1.23,
         upper.80ci = condval+condsd*1.23,
         nonzero.80ci = ifelse(lower.80ci<0&upper.80ci>0,0,1)) %>% filter(nonzero.80ci==1)

sciname.minwyppt = filter(climvarREs,grpvar=="sciname",term=="min.wy.ppt") %>% 
  select(-grpvar) %>% dplyr::rename("sciname"=grp) %>% 
  mutate(lower.95ci = condval-condsd*1.96,
         upper.95ci = condval+condsd*1.96,
         nonzero.95ci = ifelse(lower.95ci<0&upper.95ci>0,0,1),
         lower.80ci = condval-condsd*1.23,
         upper.80ci = condval+condsd*1.23,
         nonzero.80ci = ifelse(lower.80ci<0&upper.80ci>0,0,1)) %>% filter(nonzero.80ci==1)

sciname.mingsppt = filter(climvarREs,grpvar=="sciname",term=="min.gs.ppt") %>% 
  select(-grpvar) %>% dplyr::rename("sciname"=grp) %>% 
  mutate(lower.95ci = condval-condsd*1.96,
         upper.95ci = condval+condsd*1.96,
         nonzero.95ci = ifelse(lower.95ci<0&upper.95ci>0,0,1),
         lower.80ci = condval-condsd*1.23,
         upper.80ci = condval+condsd*1.23,
         nonzero.80ci = ifelse(lower.80ci<0&upper.80ci>0,0,1)) %>% filter(nonzero.80ci==1)

sciname.mingdd = filter(climvarREs,grpvar=="sciname",term=="min.gdd") %>% 
  select(-grpvar) %>% dplyr::rename("sciname"=grp) %>% 
  mutate(lower.95ci = condval-condsd*1.96,
         upper.95ci = condval+condsd*1.96,
         nonzero.95ci = ifelse(lower.95ci<0&upper.95ci>0,0,1),
         lower.80ci = condval-condsd*1.23,
         upper.80ci = condval+condsd*1.23,
         nonzero.80ci = ifelse(lower.80ci<0&upper.80ci>0,0,1))%>% filter(nonzero.80ci==1)

climVar.nonZeros = filter(select(sciname.intercepts,-term),nonzero.80ci==1) %>% 
  merge(., filter(select(sciname.maxTmean,-term),nonzero.80ci==1),by="sciname",suffixes=c(".int",".tmean"),all=T) %>% 
  merge(., filter(select(sciname.minwyppt,-term),nonzero.80ci==1),by="sciname",suffixes=c("",".wyppt"),all=T) %>% 
  merge(., filter(select(sciname.mingsppt,-term),nonzero.80ci==1),by="sciname",suffixes=c("",".gsppt"),all=T) %>% 
  merge(., filter(select(sciname.mingdd,-term),nonzero.80ci==1),by="sciname",suffixes=c("",".gdd"),all=T)

```

----

```{r plotPCA}
# partial names of climate variables in the dataset
climcols = select(dats,contains(c(".tmean",".snow",".gdd",".ppt",".pet",".aet"))) %>% names()

pcadf = dats %>% 
  select(park,summit,aspect,transition,all_of(climcols)) %>% 
  na.omit() %>% 
  unique()%>% 
  mutate(tr.num = as.numeric(str_sub(transition,4,4)))

# Look at corr plot of climate vars
climcor = cor(pcadf[c(climcols)])
corrplot::corrplot(climcor,diag=F,tl.cex=1.5)

# PCA on climate cols of climdf
climpca = prcomp(pcadf[climcols],scale. = T)
# summary(climpca)

# Plot PCA
autoplot(climpca,data=pcadf,
         loadings=TRUE,loadings.colour="grey60",
         loadings.label=T,loadings.label.size=4, colour = 'park')+
  #scale_color_viridis_d()+
  theme_bw(base_size = 14)

pcadf$aspect = factor(climdf$aspect,levels=c("N","S","E","W"))

### Look at PCs 1&2 vs climate vars
pca_df = cbind(pcadf,climpca$x) 
plot_cols = names(pca_df[,5:22])
```

----

## Excluding fishy data ##

```{r PCAmodel_withDataExclusions}

# Simplified model call from dredge output
climPC.mod.str = "endcover ~ startcover*(climPC1 + latmean1090 + I(latmean1090^2) + sitelat) + climPC2*perenneating + habit*climPC1 + habit*sitelat + (1 | transition) + (climPC1 + climPC2 | sciname)"

# Refit with REML 
climPC = lmer(formula = climPC.mod.str, na.action =  "na.fail", data = dats.scaled, REML = T)
climPC_noGSD = lmer(formula = climPC.mod.str, na.action =  "na.fail", REML = T,
                    data = subset(dats.scaled,park!="GSD"))

dats.scaled.subset = 
climPC_noFishyGenus = lmer(formula = climPC.mod.str, na.action =  "na.fail", REML = T,
                    data = filter(dats.scaled,data=!genus%in%c("Poa","Potentilla","Carex")))


tab_model(climPC,climPC_noGSD,climPC_noFishyGenus,dv.labels = c("all data","no GSD","No potentilla, poa, or carex"))
```

```{r climVar_withDataExclusions}
# Simplified model call from dredge output
climVar.mod.str = "endcover ~ startcover*(latmean1090 + I(latmean1090^2) + min.gdd + min.gs.ppt + min.wy.ppt + sitelat) + habit*(min.gdd + sitelat) + perenneating*max.tmean + (1 | transition) + (max.tmean + min.wy.ppt + min.gs.ppt + min.gdd | sciname)"

# Refit with REML 
climVar = lmer(formula = climVar.mod.str, na.action =  "na.fail", data = dats.scaled, REML = T)
climVar_noGSD = lmer(formula = climVar.mod.str, na.action =  "na.fail", REML = T,
                    data = subset(dats.scaled,park!="GSD"))
climVar_noFishyGenus = lmer(formula = climVar.mod.str, na.action =  "na.fail", REML = T,
                    data = subset(dats.scaled,!genus%in%c("Poa","Potentilla","Carex")))

tab_model(climVar,climVar_noFishyGenus,dv.labels = c("all data","No potentilla, poa, or carex"))

climVar_noGNP = lmer(formula = climVar.mod.str, na.action =  "na.fail", REML = T,
                    data = subset(dats.scaled,park!="GNP"))
climVar_noPEC = lmer(formula = climVar.mod.str, na.action =  "na.fail", REML = T,
                    data = subset(dats.scaled,park!="PEC"))
tab_model(climVar,climVar_noGNP,climVar_noPEC,dv.labels = c("all data","no GNP","no PEC"))
```







```{r}
ggplot(pcadf,aes(x=tr.num,y=mean.gs.ppt,color=summit)) +
  geom_point()+
  geom_line()+
  theme_bw() 

ggplot(subset(pcadf,park="GNP"),aes(x=park,y=mean.gs.ppt,color=transition)) +
  geom_point()+
  theme_bw()
```

